name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger workflow on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger workflow for PRs to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Set the environment for the job to run on
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Set up Node.js
        uses: actions/setup-node@v2  # Set up Node.js for the job
        with:
          node-version: '16'  # You can change the version based on your app's requirements

      - name: Install dependencies
        run: npm install  # 
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1  # Set up Docker Buildx (for advanced builds)
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2  # Log in to Docker Hub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username from GitHub secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password from GitHub secrets

      - name: Build and push Docker image
        uses: docker/build-push-action@v2  # Docker build and push action
        with:
          context: .  # Use the current directory as the context
          push: true  # Push the image to Docker Hub after build
          tags: ${{ secrets.DOCKER_USERNAME }}/hcl:latest  # Replace with your image name and tag
          
      - name: Logout from Docker Hub
        run: docker logout  # Logout from Docker Hub to clean up after the build
